StageSelectのインターフェースを明示的に実装
nkc20206086/ngs2023 pull request #11
Opened 2023-02-22 03:24 UTC by kmamonnassi

public void DoMethod → IInterface.DoMethod　のように明示的に書くように

2023-03-06 10:12 UTC, amakasuzirofight requested changes
プルリクよんだよ。ちょっと直すとこあるから見てね

2023-03-06 10:12 UTC, amakasuzirofight commented on RoboPro/Assets/Scripts/StageSelect/View/StageSelectElementView.cs
> +        public StageSelectElementInfo Info { get; private set; }
publicでinfoはちょっと考えたほうがいいかも

2023-03-07 05:40 UTC, kmamonnassi commented on RoboPro/Assets/Scripts/Settings/Model/ScreenSettings/ScreenSettings.cs
> +        public event Func<IGetSettingsData> OnGetSettingsData;
Funcを使っている理由は疎結合化を図るため。
画面設定は、画面設定の初期値を得るために設定データが必要なんだけど、
設定データを管理しているクラスを画面設定が持っている必要はないので、Funcで取り出せるようにしている。

2023-03-07 05:54 UTC, kmamonnassi commented on RoboPro/Assets/Scripts/StageSelect/View/StageSelectElementView.cs
> +        public StageSelectElementInfo Info { get; private set; }
なんでpublicにしたのかさっぱり分からない上に、変数として持っている必要がなかったから変数ごと消した

2023-03-07 06:01 UTC, kmamonnassi commented on RoboPro/Assets/Scripts/StageSelect/Test/Test_2.cs
> +    public enum CameraMode
何故かどこにも使用していなかったので削除

2023-03-07 06:01 UTC, kmamonnassi commented on RoboPro/Assets/Scripts/StageSelect/Test/Test_2.cs
> +        // ���s���e��ProjectionMatrix��v�Z����
完了

2023-03-07 06:02 UTC, kmamonnassi commented on RoboPro/Assets/Scripts/StageSelect/Entity/StageSelectModelArgs.cs
> +        public StageSelectModelArgs(List<StageSelectElementInfo> elements)
ListからIReadOnlyListに変更
Listの変更が出来ないように

2023-03-07 06:02 UTC, kmamonnassi commented on RoboPro/Assets/Scripts/Settings/View/Test/SettingsLoadTest.cs
> +public class SettingsLoadTest : MonoBehaviour
テストクラス削除

2023-03-07 06:04 UTC, kmamonnassi commented on RoboPro/Assets/Scripts/Settings/View/Audio/AudioSettingsEditView.cs
> +        public enum AudioType
AudioTypeを、AudioSettingsTypeとして新しいCSファイルとして作成

2023-03-07 06:05 UTC, kmamonnassi commented on RoboPro/Assets/Scripts/Settings/Model/Settings.cs
> +    public class Settings : ISettings
SettingsをSystemSettingsに改名
ISettingsなどのSettingsとつく名前のクラスもSystemSettingsに統一

2023-03-07 06:05 UTC, kmamonnassi commented on RoboPro/Assets/Scripts/Audio/Test/AudioPlayTest.cs
> +public class AudioPlayTest : MonoBehaviour
もう使わないと判断したのでテストクラスは削除

2023-03-07 06:13 UTC, kmamonnassi commented on RoboPro/Assets/Scripts/Audio/Data/AudioPlayBack.cs
> +        private readonly CriAtomExPlayback playBack;
playbackに変更完了

2023-03-07 06:17 UTC, kmamonnassi commented on RoboPro/Assets/Scripts/Audio/Editor/SceneAudioImporterEditor.cs
> +{
コメントアウトで詳細を明記した

2023-03-07 06:17 UTC, kmamonnassi commented on RoboPro/Assets/Scripts/StageSelect/View/StageSelectView.cs
> +        public IReadOnlyList<StageSelectElementInfo> Infos { get; private set; }
変数ごと削除

2023-03-07 06:17 UTC, kmamonnassi commented on RoboPro/Assets/Scripts/Audio/Data/CueSheetType.cs
> +
Enumの上にコメントアウトで詳細を明記

2023-03-07 06:18 UTC, kmamonnassi commented on RoboPro/Assets/Scripts/Audio/Data/AudioPlayBack.cs
> +    public class AudioPlayBack : IAudioPlayBack
明示的実装完了

2023-03-07 06:18 UTC, kmamonnassi commented on RoboPro/Assets/Scripts/Audio/Data/IAudioPlayBack.cs
> +        void Resume();
Restartに変更

2023-03-07 06:23 UTC, kmamonnassi commented on RoboPro/Assets/Scripts/Settings/Model/ISettings.cs
> +    public interface ISettings
取り敢えずISystemSettingsからISystemSettingsControllableに改名
正直、将来的にセーブ以外のことをやらせる場合のことを考えるとISaveDataControllableにはしたくない感があるかな…

2023-03-07 06:31 UTC, kmamonnassi commented on RoboPro/Assets/Scripts/Audio/Data/AudioPlayBack.cs
> +        private readonly CriAtomExPlayback playBack;
https://github.com/nkc20206086/ngs2023/blob/d7cf4010bbf2c4ef3f3f71b6d460fdc59200df3f/RoboPro/Assets/Scripts/Audio/Data/AudioPlayBack.cs#L5

2023-03-07 06:32 UTC, kmamonnassi commented on RoboPro/Assets/Scripts/Audio/Data/AudioPlayBack.cs
> +    public class AudioPlayBack : IAudioPlayBack
https://github.com/nkc20206086/ngs2023/blob/d7cf4010bbf2c4ef3f3f71b6d460fdc59200df3f/RoboPro/Assets/Scripts/Audio/Data/AudioPlayBack.cs#L14-L30

2023-03-07 06:34 UTC, kmamonnassi commented on RoboPro/Assets/Scripts/Audio/Data/IAudioPlayBack.cs
> +        void Resume();
https://github.com/nkc20206086/ngs2023/blob/d7cf4010bbf2c4ef3f3f71b6d460fdc59200df3f/RoboPro/Assets/Scripts/Audio/Data/IAudioPlayBack.cs#L9-L10

2023-03-07 06:42 UTC, kmamonnassi commented on RoboPro/Assets/Scripts/Audio/Data/CueSheetType.cs
> +
https://github.com/nkc20206086/ngs2023/blob/986b9fc4d5175bcec9ac5c69b4f1e80adab3f2d8/RoboPro/Assets/Scripts/Audio/Data/CueSheetType.cs#L3-L19

2023-03-07 06:43 UTC, kmamonnassi commented on RoboPro/Assets/Scripts/Audio/Editor/SceneAudioImporterEditor.cs
> +{
https://github.com/nkc20206086/ngs2023/blob/c238299c56989b01f832dfe71bd4d4e69b29a605/RoboPro/Assets/Scripts/Audio/Editor/SceneAudioImporterEditor.cs#L14-L23

2023-03-07 06:45 UTC, kmamonnassi commented on RoboPro/Assets/Scripts/Settings/View/Audio/AudioSettingsEditView.cs
> +        public enum AudioType
https://github.com/nkc20206086/ngs2023/blob/ede0225f6c7be3fe7da4e3ae0cca6b67d990d65d/RoboPro/Assets/Scripts/Settings/View/Audio/AudioSettingsType.cs#L1-L9

2023-03-07 06:47 UTC, kmamonnassi commented on RoboPro/Assets/Scripts/StageSelect/View/StageSelectElementView.cs
> +        public StageSelectElementInfo Info { get; private set; }
https://github.com/nkc20206086/ngs2023/blob/72937aa173137c30b95e770e9fa77d6266f578a3/RoboPro/Assets/Scripts/StageSelect/View/StageSelectElementView.cs#L25-L34

2023-03-07 06:48 UTC, kmamonnassi commented on RoboPro/Assets/Scripts/StageSelect/Entity/StageSelectModelArgs.cs
> +        public StageSelectModelArgs(List<StageSelectElementInfo> elements)
https://github.com/nkc20206086/ngs2023/blob/72937aa173137c30b95e770e9fa77d6266f578a3/RoboPro/Assets/Scripts/StageSelect/Entity/StageSelectModelArgs.cs#L10

2023-03-09 23:19 UTC, merged